output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value       = module.eks.cluster_security_group_id
}

output "cluster_id" {
  description = "Kubernetes Cluster Name"
  value       = module.eks.cluster_id
}

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = module.eks.kubeconfig
# }

# output "config_map_aws_auth" {
#   description = "A kubernetes configuration to authenticate to this EKS cluster."
#   value       = module.eks.config_map_aws_auth
# }

output "oidc_arn" {
  description = "OIDC Irsa ARN"
  value       = module.eks.oidc_provider_arn
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = data.aws_eks_cluster.default.id
}

output "configure_kubeconfig" {
  description = "Command to configure kubeconfig"
  value       = "aws eks --region $(terraform output region) update-kubeconfig --name $(terraform output cluster_name)"
}